---
title: STAT 4354 Homework 3
author: Steven Chiou
output: pdf_document
urlcolor: blue
geometry: "top = 1cm"
always_allow_html: yes
---

\begin{center}
Due date: Monday, March 8
\end{center}


**Submission instructions:**

  - This assignment is due to our grader, Zhiwei Zhen (zxz190002@utdallas.edu)
    by 11:59 pm, Monday, March 8. 
  - Please submit a `Rmd` file and a `pdf` file generated by R markdown.
  - Name your file `LastName4354hw3.pdf` and `LastName4354hw3.Rmd`, for example, `Chiou4354hw3.pdf` and `Chiou4354hw3.Rmd`.
  - The following submission policies will apply unless you have an emergency note:
      - Submission on Tuesday, March 9, will be considered late and will be penalized (50\% penalty).
      - Submission after Tuesday, March 9, will not be graded and be counted as a 0.
  - Please indicate by number which questions you are answering.
  - Please include a random seed if you use random number generators.
  - Start a problem in a new page, e.g., `\newpage`.

**Questions:** 

```{R setup, include = FALSE}
knitr::opts_chunk$set(comment = NA, prompt = TRUE, collapse = TRUE)
```

1. (2 pts) Two gamblers, Tom and Jerry, bet on the outcomes of successive flips of a fair coin.
On each flip, if the coin lands on heads, Tom collects \$1.00 from Jerry. 
If the coin lands on tail, Tom pays \$1.00 to Jerry. 
They continue to do this until one of them runs out of money. 
Assume the successive flips of the coin are independent.
Use simulation with 10,000 replications to find the probability that Tom winds up with all the money if 
Tom starts with \$5.00 and Jerry starts with \$2.00. \label{coin}

2. (2 pts) 
Suppose the coin in \#\ref{coin} is a biased coin that lands on head with probability 20\%.
Use simulation with 10,000 replications to find the probability that Tom winds up with all the money if 
Tom starts with \$5.00 and Jerry starts with \$2.00. 

3. (2 pts)
Consider two random variables $X$ and $Y$ that satisfy the following conditions:

    - Var(X) = 4 Var(Y)
    - E(X) = E(Y) = 0
    - E(XY) = 0.5Var(Y)
  
    Define $U = X + aY$ and $W = X - aY$ for some constant $a$. Find $a$ so that $E(UW) = 0$.
    
4. (2 pts)
Let $X$ be a discrete uniform random variable with the probability mass function
$$P(X = x) = \frac{1}{k}, \mbox{ for }x = 1, 2, \ldots, k,$$
where $k = 1000$. Find E$[e^{(X/k)}]$ by definition and by simulation. \label{unif}

5. (2 pts)
Under the setup describe in \#\ref{unif}. 
Find Var$[e^{(X/k)}]$ by definition and by simulation. 